[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "harpoon"
dynamic = ["version"]
description = "Another OSINT CLI tool"
readme = "README.md"
license = { text = "GPLv3" }
authors = [
    { name = "Tek", email = "tek@randhome.io" },
]
keywords = ["security", "osint", "threatintelligence"]
classifiers = [
    "Intended Audience :: Information Technology",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
requires-python = ">= 3.9"
dependencies = [
    "IPy",
    "requests",
    "consolemd",
    "appdirs",
    "rich",
    "maxminddb",
]

[project.optional-dependencies]
docs = ["mkdocs"]

[project.urls]
Homepage = "https://github.com/te-k/harpoon"

[project.scripts]
harpoon = "harpoon.cli:cli"

[tool.setuptools.dynamic]
version = { attr = "harpoon.version.HARPOON_VERSION" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
harpoon = ["data/*.conf"]

[tool.ruff]
# Never enforce `E501` (line length violations).
lint.ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
ignore_missing_imports = true

[tool.isort]
profile = "black"
